title: Mahesh Shivanna
description: >
  Software Developer
company: SAP Labs
company_url: https://www.sap.com/india/about/company/innovation/labs.html
sass:
  sass_dir: assets/sass
url: http://maheshiv.github.io
disqus_shortname: maheshiv
phone_no: 8951152660
twitter_username: maheshivanna
linkedin_username: maheshivanna
cv: maheshivanna
stackoverflow: maheshiv
aboutme: maheshivanna
instagram_username:
pinterest_username:
flickr_username:
github_username:  maheshiv
feed_icon:
email: maheshivanna@gmail.com
gems: [jekyll-paginate]
paginate_path: "/page/:num/"
paginate: 5

theme: jekyll-theme-tactile