title: Mahesh Shivanna
description: >
  I am Mahesh, working as a Javascript Programmer for AfterNow under the payroll of Read-Ink Technologies.
  This is my personal blog site.
sass:
  sass_dir: assets/sass
url: http://maheshiv.github.io
disqus_shortname: disqus_oIcR0XrguT
phone_no: 8951152660
twitter_username: LSMahesh
linkedin_username: maheshivanna
cv: maheshivanna
stackoverflow: maheshiv
instagram_username:
pinterest_username:
flickr_username:
github_username:  maheshiv
feed_icon:
email: maheshivanna@gmail.com
gems: [jekyll-paginate]
paginate_path: "/page/:num/"
paginate: 5
