title: Mahesh Shivanna
description: >
  Javascript Programmer
company: AfterNow
company_url: http://www.afternow.io
sass:
  sass_dir: assets/sass
url: http://maheshiv.github.io
disqus_shortname: maheshiv
phone_no: 8951152660
twitter_username: LSMahesh
linkedin_username: maheshivanna
cv: maheshivanna
stackoverflow: maheshiv
aboutme: maheshivanna
instagram_username:
pinterest_username:
flickr_username:
github_username:  maheshiv
feed_icon:
email: maheshivanna@gmail.com
gems: [jekyll-paginate]
paginate_path: "/page/:num/"
paginate: 5
